Charles Darwin: one-move-win euristics e random
specialfish9/unibo_37635_MNK pull request #3
Opened 2021-07-31 14:55 UTC by lucat1

Sto ancora facendo i test, comunque e' pari a Bertrand ma semplicemente molto piu' veloce. Dovrebbe dargli un vantaggio in giochi tipo `S=10x10 constrained(1)` pero' ancora non ne ho notato. Per il resto eseguendo semplicemente `make test(1)` si vede quanto quando inzia `Bertrand` visita ~170k griglie mentre `Charles` solo ~3k
<details>
  <summary>(10,10,10) constrained</summary>
<code><pre>
mkdir -p build
javac -cp src -d build src/mnkgame/*.java src/mnkgame/players/*.java
java  -cp build mnkgame.MNKPlayerTester 10 10 10 mnkgame.players.BertrandRussell mnkgame.players.CharlesDarwin -v -t 1 -r 5
Game type : 10,10,10
Player1   : Bertrand Russell
Player2   : Charles Darwin
Rounds    : 5
Timeout   : 1 secs

**** ROUND 1 ****
Initializing 10,10,10 board
Initializing Bertrand Russell as Player 1
Initializing Charles Darwin as Player 2

Bertrand Russell	: visited 1233896 nodes, ended with result: (4.9E-324,[4,3] -> FREE)
Player 1 (Bertrand Russell) -> [4,3]
Charles Darwin	: visited 573419 nodes, ended with result: (0.0,[8,4] -> FREE)
Player 2 (Charles Darwin) -> [8,4]
Bertrand Russell	: visited 1849575 nodes, ended with result: (4.9E-324,[3,1] -> FREE)
Player 1 (Bertrand Russell) -> [3,1]
Charles Darwin	: visited 656758 nodes, ended with result: (0.0,[7,0] -> FREE)
Player 2 (Charles Darwin) -> [7,0]
Bertrand Russell	: visited 1856497 nodes, ended with result: (4.9E-324,[2,6] -> FREE)
Player 1 (Bertrand Russell) -> [2,6]
Charles Darwin	: visited 658815 nodes, ended with result: (0.0,[9,8] -> FREE)
Player 2 (Charles Darwin) -> [9,8]
Bertrand Russell	: visited 1849813 nodes, ended with result: (4.9E-324,[8,5] -> FREE)
Player 1 (Bertrand Russell) -> [8,5]
Charles Darwin	: visited 583574 nodes, ended with result: (0.0,[9,2] -> FREE)
Player 2 (Charles Darwin) -> [9,2]
Bertrand Russell	: visited 1679841 nodes, ended with result: (4.9E-324,[1,6] -> FREE)
Player 1 (Bertrand Russell) -> [1,6]
Charles Darwin	: visited 621672 nodes, ended with result: (0.0,[6,8] -> FREE)
Player 2 (Charles Darwin) -> [6,8]
Bertrand Russell	: visited 1677446 nodes, ended with result: (4.9E-324,[2,1] -> FREE)
Player 1 (Bertrand Russell) -> [2,1]
Charles Darwin	: visited 602744 nodes, ended with result: (0.0,[7,6] -> FREE)
Player 2 (Charles Darwin) -> [7,6]
Bertrand Russell	: visited 1728012 nodes, ended with result: (4.9E-324,[5,8] -> FREE)
Player 1 (Bertrand Russell) -> [5,8]
Charles Darwin	: visited 624494 nodes, ended with result: (0.0,[5,4] -> FREE)
Player 2 (Charles Darwin) -> [5,4]
Bertrand Russell	: visited 1806750 nodes, ended with result: (4.9E-324,[9,0] -> FREE)
Player 1 (Bertrand Russell) -> [9,0]
Charles Darwin	: visited 608068 nodes, ended with result: (0.0,[6,2] -> FREE)
Player 2 (Charles Darwin) -> [6,2]
Bertrand Russell	: visited 1732405 nodes, ended with result: (4.9E-324,[9,7] -> FREE)
Player 1 (Bertrand Russell) -> [9,7]
Charles Darwin	: visited 575614 nodes, ended with result: (0.0,[0,1] -> FREE)
Player 2 (Charles Darwin) -> [0,1]
Bertrand Russell	: visited 1730469 nodes, ended with result: (4.9E-324,[3,6] -> FREE)
Player 1 (Bertrand Russell) -> [3,6]
Charles Darwin	: visited 607367 nodes, ended with result: (0.0,[1,5] -> FREE)
Player 2 (Charles Darwin) -> [1,5]
Bertrand Russell	: visited 1732770 nodes, ended with result: (4.9E-324,[2,8] -> FREE)
Player 1 (Bertrand Russell) -> [2,8]
Charles Darwin	: visited 630494 nodes, ended with result: (0.0,[2,3] -> FREE)
Player 2 (Charles Darwin) -> [2,3]
Bertrand Russell	: visited 1694523 nodes, ended with result: (4.9E-324,[8,2] -> FREE)
Player 1 (Bertrand Russell) -> [8,2]
Charles Darwin	: visited 631808 nodes, ended with result: (0.0,[0,7] -> FREE)
Player 2 (Charles Darwin) -> [0,7]
Bertrand Russell	: visited 1737759 nodes, ended with result: (4.9E-324,[6,3] -> FREE)
Player 1 (Bertrand Russell) -> [6,3]
Charles Darwin	: visited 621946 nodes, ended with result: (0.0,[4,5] -> FREE)
Player 2 (Charles Darwin) -> [4,5]
Bertrand Russell	: visited 1744299 nodes, ended with result: (4.9E-324,[4,8] -> FREE)
Player 1 (Bertrand Russell) -> [4,8]
Charles Darwin	: visited 589759 nodes, ended with result: (0.0,[6,1] -> FREE)
Player 2 (Charles Darwin) -> [6,1]
Bertrand Russell	: visited 1698214 nodes, ended with result: (4.9E-324,[1,1] -> FREE)
Player 1 (Bertrand Russell) -> [1,1]
Charles Darwin	: visited 621028 nodes, ended with result: (0.0,[2,9] -> FREE)
Player 2 (Charles Darwin) -> [2,9]
Bertrand Russell	: visited 1587236 nodes, ended with result: (4.9E-324,[0,6] -> FREE)
Player 1 (Bertrand Russell) -> [0,6]
Charles Darwin	: visited 565269 nodes, ended with result: (0.0,[8,9] -> FREE)
Player 2 (Charles Darwin) -> [8,9]
Bertrand Russell	: visited 1681521 nodes, ended with result: (4.9E-324,[4,1] -> FREE)
Player 1 (Bertrand Russell) -> [4,1]
Charles Darwin	: visited 599386 nodes, ended with result: (0.0,[0,2] -> FREE)
Player 2 (Charles Darwin) -> [0,2]
Bertrand Russell	: visited 1593361 nodes, ended with result: (4.9E-324,[1,4] -> FREE)
Player 1 (Bertrand Russell) -> [1,4]
Charles Darwin	: visited 591781 nodes, ended with result: (0.0,[9,3] -> FREE)
Player 2 (Charles Darwin) -> [9,3]
Bertrand Russell	: visited 1722074 nodes, ended with result: (4.9E-324,[0,9] -> FREE)
Player 1 (Bertrand Russell) -> [0,9]
Charles Darwin	: visited 569078 nodes, ended with result: (0.0,[7,7] -> FREE)
Player 2 (Charles Darwin) -> [7,7]
Bertrand Russell	: visited 1653603 nodes, ended with result: (4.9E-324,[5,5] -> FREE)
Player 1 (Bertrand Russell) -> [5,5]
Charles Darwin	: visited 599456 nodes, ended with result: (0.0,[2,4] -> FREE)
Player 2 (Charles Darwin) -> [2,4]
Bertrand Russell	: visited 1734842 nodes, ended with result: (4.9E-324,[8,0] -> FREE)
Player 1 (Bertrand Russell) -> [8,0]
Charles Darwin	: visited 593200 nodes, ended with result: (0.0,[4,6] -> FREE)
Player 2 (Charles Darwin) -> [4,6]
Bertrand Russell	: visited 1605137 nodes, ended with result: (4.9E-324,[5,1] -> FREE)
Player 1 (Bertrand Russell) -> [5,1]
Charles Darwin	: visited 555209 nodes, ended with result: (0.0,[9,9] -> FREE)
Player 2 (Charles Darwin) -> [9,9]
Bertrand Russell	: visited 1703124 nodes, ended with result: (4.9E-324,[6,0] -> FREE)
Player 1 (Bertrand Russell) -> [6,0]
Charles Darwin	: visited 549177 nodes, ended with result: (0.0,[0,8] -> FREE)
Player 2 (Charles Darwin) -> [0,8]
Bertrand Russell	: visited 1539123 nodes, ended with result: (4.9E-324,[8,8] -> FREE)
Player 1 (Bertrand Russell) -> [8,8]
Charles Darwin	: visited 572876 nodes, ended with result: (0.0,[4,0] -> FREE)
Player 2 (Charles Darwin) -> [4,0]
Bertrand Russell	: visited 1537443 nodes, ended with result: (4.9E-324,[7,8] -> FREE)
Player 1 (Bertrand Russell) -> [7,8]
Charles Darwin	: visited 580288 nodes, ended with result: (0.0,[8,3] -> FREE)
Player 2 (Charles Darwin) -> [8,3]
Bertrand Russell	: visited 1679885 nodes, ended with result: (4.9E-324,[3,8] -> FREE)
Player 1 (Bertrand Russell) -> [3,8]
Charles Darwin	: visited 592230 nodes, ended with result: (0.0,[6,7] -> FREE)
Player 2 (Charles Darwin) -> [6,7]
Bertrand Russell	: visited 1585051 nodes, ended with result: (4.9E-324,[3,5] -> FREE)
Player 1 (Bertrand Russell) -> [3,5]
Charles Darwin	: visited 530741 nodes, ended with result: (0.0,[0,3] -> FREE)
Player 2 (Charles Darwin) -> [0,3]
Bertrand Russell	: visited 1575094 nodes, ended with result: (4.9E-324,[3,4] -> FREE)
Player 1 (Bertrand Russell) -> [3,4]
Charles Darwin	: visited 586499 nodes, ended with result: (0.0,[1,7] -> FREE)
Player 2 (Charles Darwin) -> [1,7]
Bertrand Russell	: visited 1537586 nodes, ended with result: (4.9E-324,[1,8] -> FREE)
Player 1 (Bertrand Russell) -> [1,8]
Charles Darwin	: visited 573681 nodes, ended with result: (0.0,[3,0] -> FREE)
Player 2 (Charles Darwin) -> [3,0]
Bertrand Russell	: visited 1505607 nodes, ended with result: (4.9E-324,[7,2] -> FREE)
Player 1 (Bertrand Russell) -> [7,2]
Charles Darwin	: visited 527400 nodes, ended with result: (0.0,[2,5] -> FREE)
Player 2 (Charles Darwin) -> [2,5]
Bertrand Russell	: visited 1628183 nodes, ended with result: (4.9E-324,[1,9]  [...]

2021-07-31 15:53 UTC, lucat1 commented
Se guardi a `constrained` e `constrained1` la differenza e' notevole, `Bertrand` fa `162989` visite mentre `Charles` ne fa `3414` al primo turno

2021-08-01 08:40 UTC, specialfish9 requested changes
Me par ben

2021-08-01 08:40 UTC, specialfish9 commented on src/mnkgame/players/BertrandRussell.java
> +    public String toString() {
Puro e inutile formalismo: potresti aggiungere @Override ?

2021-08-01 08:40 UTC, specialfish9 commented on src/mnkgame/players/CharlesDarwin.java
> +    public String toString() {
same

2021-08-01 08:40 UTC, specialfish9 commented on src/mnkgame/players/CharlesDarwin.java
>        return new Pair<>(HALT, board.getFreeCells()[0]);
Possiamo ritornarne una random? Non dovrebbe cambiare molto ma affidiamo la cosa alla dea bendata 😆

2021-08-01 08:40 UTC, specialfish9 commented on src/mnkgame/players/CharlesDarwin.java
> +      if(b <= a)
siamo stati poco furbi a non metterlo prima, ben fatto 👍🏼

2021-08-01 08:40 UTC, specialfish9 commented on src/mnkgame/players/CharlesDarwin.java
> -    List<MNKCell> free_cells = new ArrayList<>(Arrays.asList(board.getFreeCells()));
Siamo sicuri che sia il modo più furbo per shuffle-are un array?

2021-08-01 08:48 UTC, lucat1 commented on src/mnkgame/players/CharlesDarwin.java
>        return new Pair<>(HALT, board.getFreeCells()[0]);
ah no no ma è giusto così perché la coppia che ritorni è del tipo <valore della board finale, mossa che ti ha portato alla cella> e in quel caso l’ultima mossa è quella che ti ha portato a quello stato. però non cambierebbe perché tanto viene ignorato questo valore nelle chiamate ricorsive che ci hanno portati fino a questo punto.

TL;DR prima usavo null, e va bene uguale, era per completezza ma posso mettere quello che voglio non cambia perché viene ignorato

2021-08-01 08:48 UTC, lucat1 commented on src/mnkgame/players/CharlesDarwin.java
> +      if(b <= a)
Eh l’ho notato da un sito, mi sa che di lena non l’aveva messo l’uguale

2021-08-01 08:50 UTC, lucat1 commented on src/mnkgame/players/CharlesDarwin.java
> -    List<MNKCell> free_cells = new ArrayList<>(Arrays.asList(board.getFreeCells()));
Questo non lo shuffla, la riga dopo mi pare si. Comunque andrà cambiato in futuro quando piazzeremo prima le celle vicine alle posizioni già giocare e poi quelle più lontane, quindi io ora l’ho messo ma è da cambiare

2021-08-01 08:51 UTC, specialfish9 commented on src/mnkgame/players/CharlesDarwin.java
> -    List<MNKCell> free_cells = new ArrayList<>(Arrays.asList(board.getFreeCells()));
perfettto, ti ho pushato un metodo che lo fa in \tetha(n) senza dover converire a Collection

2021-08-01 08:52 UTC, specialfish9 commented on src/mnkgame/players/CharlesDarwin.java
> +      if(b <= a)
Ho controllato, anche di lena l'aveva messo lol

2021-08-01 08:53 UTC, specialfish9 commented on src/mnkgame/players/CharlesDarwin.java
>        return new Pair<>(HALT, board.getFreeCells()[0]);
E scusa se succede l'HALT che mossa scegliamo quindi?

2021-08-01 08:56 UTC, merged

2021-08-01 09:16 UTC, lucat1 commented
Mancava una euristica ma no problem la faccio dopo e apro un’altra pr